name: god_father
description: "A new Flutter project."



version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.6.4
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value turf_equality:
  equatable: ^2.0.5
  # functional programming thingies
  dartz: ^0.10.1
  # Remote API
  data_connection_checker_nulls: ^0.0.2
  http: ^1.1.2
  # local cache
  shared_preferences: ^2.2.2
  # Navigator

  go_router: ^14.2.0
#  auto_route: ^7.8.4

  # this list has ability to scroll to specific index
  scrollable_positioned_list: ^0.3.8

  cupertino_icons: ^1.0.2

  # Side drawer
#  inner_drawer: ^1.0.0+1
  inner_drawer:
    path: /Users/mac/Desktop/inner_drawer-main-2
#    git:
#      url: https://github.com/j1pishraft/test.git

  flutter_localizations:
    sdk: flutter
  intl: any

  hidden_drawer_menu: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  build_runner: ^2.4.7
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.13.1
#  auto_route_generator: ^7.3.2


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true # Add this line
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/locales/en.json
    - assets/locales/fa.json
    - config/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
